### PR TITLE
Add minimal kqueue support

### PR DESCRIPTION
**Pull request by tokenrove**
This change is [Reviewable](https://reviewable.io/reviews/tokenrove/erl-dirwatch/1)

### CODE REVIEW

**Comment by RAttab** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/dirwatch.erl, line 56 [r2]](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1#-KNgsPVveD0v6ZlXGYfZ:-KNgsPVveD0v6ZlXGYf_:607508286) ([raw file](https://github.com/tokenrove/erl-dirwatch/blob/1652ad16e48519e8bea586d1965c8d7d495d2f2c/src/dirwatch.erl#L56)):_

> ``` Erlang
>     ok = load(),
>     Port = open_port({spawn_driver,
>                       ["dirwatch ", integer_to_list(CooldownMs, 10), $ , Path]},
> ```

`$\s` might be a little less confusing.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1)_

**Comment by RAttab** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1#-:-KNgsoKwV9Uw6FqOmMHL:1417088721)_

**Comment by tokenrove** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/dirwatch.erl, line 56 [r2]](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1#-KNgsPVveD0v6ZlXGYfZ:-KNgvGh3_yBIMdsH0hqx:-1695905326) ([raw file](https://github.com/tokenrove/erl-dirwatch/blob/1652ad16e48519e8bea586d1965c8d7d495d2f2c/src/dirwatch.erl#L56)):_
<details><summary>

<i>Previously, RAttab (Rémi Attab) wrote…</i></summary>



> `$\s` might be a little less confusing.
> </details>
> Yeah.  I guess I'm used to `$` as a common Erlang convention, but you're right that it doesn't read well.  On the other hand, I don't think I've ever seen `$\s`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1)_

**Comment by RAttab** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---

_[src/dirwatch.erl, line 56 [r2]](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1#-KNgsPVveD0v6ZlXGYfZ:-KNhR_0ynSsa1Vrh_SKG:-1655238110) ([raw file](https://github.com/tokenrove/erl-dirwatch/blob/1652ad16e48519e8bea586d1965c8d7d495d2f2c/src/dirwatch.erl#L56)):_
<details><summary>

<i>Previously, tokenrove (Julian Squires) wrote…</i></summary>



> Yeah.  I guess I'm used to `$` as a common Erlang convention, but you're right that it doesn't read well.  On the other hand, I don't think I've ever seen `$\s`.
> </details>
> For someone no 100% used to erlang it took me a sec to figure out what it meant. I've used `$\s` just because I think it's less weird but I don't mind either way.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1)_

**Comment by RAttab** [comment]
Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/erl-dirwatch/1)_

**Pull request merged**
